version: "3"

services:

  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASS=$POSTGRES_PASS

  webapp:
    restart: unless-stopped
    image: mattdexter/mattdexter-webapp:latest
    build: ./webapp
    volumes:
      - ./webapp:/src
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_STATIC_ROOT=$DJANGO_STATIC_ROOT
      - GUNICORN_WORKERS=$GUNICORN_WORKERS
      - GUNICORN_BIND=$GUNICORN_BIND
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - VIRTUAL_HOST=$VIRTUAL_HOST
    depends_on:
      - postgres

  nginx-proxy:
    restart: unless-stopped
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
      - ./webapp/static:/src/static
    depends_on:
      - webapp

volumes:
  data: