version: "3"

services:

  postgres:
    restart: unless-stopped
    image: postgres:latest
    container_name: postgres
    volumes:
      - pdata:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASS=$POSTGRES_PASS

  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mdata:/var/lib/mongodb/data
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=$MONGO_DATA_DIR
    depends_on:
      - postgres

  webapp:
    restart: unless-stopped
    image: mattdexter/mattdexter-webapp:latest
    container_name: webapp
    build: ./webapp
    volumes:
      - ./webapp:/src
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_STATIC_ROOT=$DJANGO_STATIC_ROOT
      - GUNICORN_WORKERS=$GUNICORN_WORKERS
      - GUNICORN_BIND=$GUNICORN_BIND
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    depends_on:
      - postgres
      - mongodb

  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /etc/nginx/html:/usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - ./webapp/static:/src/static
    depends_on:
      - webapp

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: dockergen
    restart: unless-stopped
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /etc/nginx/html:/usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./webapp/static:/src/static
    depends_on:
      - nginx

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /etc/nginx/html:/usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./webapp/static:/src/static
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "dockergen"
      NGINX_PROXY_CONTAINER: "nginx"
    depends_on:
      - nginx
      - dockergen

volumes:
  pdata:
  mdata: