version: "3"

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASS=$POSTGRES_PASS
      - POSTGRES_DB=$POSTGRES_DB

  web:
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_STATIC_ROOT=$DJANGO_STATIC_ROOT
      - GUNICORN_WORKERS=$GUNICORN_WORKERS
      - GUNICORN_BIND=$GUNICORN_BIND
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - .:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_SERVER_NAME=$NGINX_SERVER_NAME
    depends_on:
      - web