webapp:
  restart: always
  build: ./webapp/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: env
  volumes:
    - ./webapp:/data/webapp
  working_dir: /data/webapp/mattdexter

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - webapp
  links:
    - webapp:webapp

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./backups/postgresql:/backup
  env_file: env
  expose:
    - "5432"

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"

data:
  restart: always
  image: python:3-alpine
  volumes:
    - /var/lib/postgresql
  command: "true"