web:
  restart: always
  build: ./web/
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /data/web/static
  expose:
    - "8000"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web:web
  volumes_from:
    - web

postgres:
  restart: always
  image: postgres
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  volumes_from:
    - data
  environment:
    - POSTGRES_USER=mattdexter_web
    - POSTGRES_PASS=mattdexter_web
    - POSTGRES_NAME=mattdexter_web
  expose:
    - "5432"

data:
  restart: always
  image: python:3-alpine
  volumes:
    - /var/lib/postgresql
  command: "true"

redis:
  restart: always
  image: redis
  expose:
    - "6379"