# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171121_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='schooling',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='schooling',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='date_modified',
        ),
    ]
